# Sistemas dimámicos dos dimensionales

In [2]:
A=[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [8]:
vecs=eigvecs(A)

2×2 Array{Float64,2}:
 -0.824565  -0.415974
  0.565767  -0.909377

In [11]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [12]:
?eigvecs

search: eigvecs



```
eigvecs(A, [eigvals,][permute=true,][scale=true]) -> Matrix
```

Returns a matrix `M` whose columns are the eigenvectors of `A`. (The `k`th eigenvector can be obtained from the slice `M[:, k]`.) The `permute` and `scale` keywords are the same as for [`eigfact`](:func:`eigfact`).

For [`SymTridiagonal`](:class:`SymTridiagonal`) matrices, if the optional vector of eigenvalues `eigvals` is specified, returns the specific corresponding eigenvectors.

```
eigvecs(A, B) -> Matrix
```

Returns a matrix `M` whose columns are the generalized eigenvectors of `A` and `B`. (The `k`th eigenvector can be obtained from the slice `M[:, k]`.)

```jldoctest
julia> A = [1 0; 0 -1]
2×2 Array{Int64,2}:
 1   0
 0  -1

julia> B = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> eigvecs(A, B)
2×2 Array{Complex{Float64},2}:
  0.0-1.0im   0.0+1.0im
 -1.0-0.0im  -1.0+0.0im
```


$$\frac{d \vec x}{d t}=A \vec x,$$
con $A=\left(\begin{array}{cc} a & b \\c & d \end{array} \right)$

![](images/fixed_points_space.png)

## Algebra lineal en Julia