Documentación: http://docs.julialang.org/en/release-0.6/manual/modules/

* Esquema general de una libreria (modulo), digamos MyModule.jl

__module MyModule__ _(nombre del modulo)_

__using package1, package2__ _(Aqui llamamos los paquetes que nuestro modulo necesita para funcionar)_

__export x, y__ _(las funciones que exportamos al workspace cuando llamamos al modulo)_

__x() = "x"__

__y() = "y"__

__p() = "p"__ _(Nótese que la funcion p() no esta exportada, podemos definir funciones de uso interno, esta no aparcera en el workspace con el comando "using MyModule", sin embargo será accesible con "import MyModule")_

__end__

In [4]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export metodo_newton

function metodo_newton(f,df,x0)
    x=x0
    for i in 1:20
       x=x-f(x)/df(x) 
    end
    return x
end

end

herramientas

In [5]:
herramientas.metodo_newton(x->x^2-2,x->2*x,1)

1.414213562373095

In [6]:
pwd() # Con este comando podemos ver la ruta de este notebook

"/home/juser/Fisica_computacional_2018-1/clases"

In [1]:
push!(LOAD_PATH, "/home/juser/Fisica_computacional_2018-1/clases")

5-element Array{Any,1}:
 "/opt/julia-0.6.0/local/share/julia/site/v0.6"  
 "/opt/julia-0.6.0/share/julia/site/v0.6"        
 "/opt/julia_packages/.julia/v0.6/"              
 "/home/juser/Fisica_computacional_2018-1/clases"
 "/home/juser/Fisica_computacional_2018-1/clases"

In [ ]:
push!(LOAD_PATH, "/home/juser/Fisica_computacional_2018-1/clases")


In [3]:
;"push!(LOAD_PATH, "/home/juser/Fisica_computacional_2018-1/clases")" >> ~/.juliarc.jl

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] warn_shell_special(::String) at ./shell.jl:8
 [3] #shell_parse#236(::String, ::Function, ::String, ::Bool) at ./shell.jl:103
 [4] (::Base.#kw##shell_parse)(::Array{Any,1}, ::Base.#shell_parse, ::String, ::Bool) at ./<missing>:0 (repeats 2 times)
 [5] @cmd(::ANY) at ./process.jl:796
 [6] include_string(::String, ::String) at ./loading.jl:515
 [7] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /opt/julia_packages/.julia/v0.6/IJulia/src/execute_request.jl:160
 [8] eventloop(::ZMQ.Socket) at /opt/julia_packages/.julia/v0.6/IJulia/src/eventloop.jl:8
 [9] (::IJulia.##11#14)() at ./task.jl:335
while loading In[3], in expression starting on line 1
/bin/sh: 1: push!(LOAD_PATH, /home/juser/Fisica_computacional_2018-1/clases): not found


In [1]:
LOAD_PATH

4-element Array{Any,1}:
 "/opt/julia-0.6.0/local/share/julia/site/v0.6"  
 "/opt/julia-0.6.0/share/julia/site/v0.6"        
 "/opt/julia_packages/.julia/v0.6/"              
 "/home/juser/Fisica_computacional_2018-1/clases"

In [7]:
push!(LOAD_PATH, 
pwd())

5-element Array{Any,1}:
 "/opt/julia-0.6.0/local/share/julia/site/v0.6"  
 "/opt/julia-0.6.0/share/julia/site/v0.6"        
 "/opt/julia_packages/.julia/v0.6/"              
 "/home/juser/Fisica_computacional_2018-1/clases"
 "/home/juser/Fisica_computacional_2018-1/clases"

In [2]:
using herramientas

In [3]:
metodo_newton(x->x^2-2,x->2*x,1)

1.414213562373095

In [1]:
;cd herramientas/src

/home/juser/Fisica_computacional_2018-1/clases/herramientas/src


In [2]:
;ls

herramientas.jl


In [6]:
import herramientas.jl